### ISSUE TITLE
Not working anymore on Tumblr + add url

### ISSUE THREAD

**Issue by Micha-MHX** [eramdam/GifsOnTumblr#3]
It does not work anymore for me on tumblr dashboard pages, I suddenly get gifv again which Firefox wants to save as webp, so I need to open the image and replace gifv manually in url by gif.

And if I right-click on the image and select "show image", in the address bar it shows https://66.media.tumblr.com/ for example, maybe for this case you want to add urk *.media.tumblr.com?

**Comment by ZaCloud** [comment]
I'm guessing it's because tumblr just completely overhauled their code structure. But I do hope a solution will be in the works soon. I only got to enjoy this for a couple weeks. ^^;;

On my end, on Chrome, my old workaround consists of right-clicking and opening image in a new tab. This changes the extension to .gifv. Then you just delete the "v" on the end and hit Enter, and it reopens as a .gif, which you can then save.

**Comment by eramdam** [comment]
Only seeing this now 😅 

But I _think_ it should be fixed by the fix for https://github.com/eramdam/GifsOnTumblr/issues/4 ? 

You can look out for 1.1.1 which is live on [Firefox](https://addons.mozilla.org/en-US/firefox/addon/gifsontumblr/).

**Comment by Micha-MHX** [comment]
Yes, you are right, the new version fixes it. Thanks!
